# Configuration file for the global attributes to be written to the CF-NetCDF file
# Please fill in values next to the "value" key for each attribute
# Attributes commented out will be ignored
# Attributes with the "value" not stated will be ignored
# The following attributes are written to the file within the script, so you do not need to include values here
# geospatial_lat_min, geospatial_lat_max, geospatial_lon_min, geospatial_lon_max, date_created, history
# If you include values for these attributes, this will override the values written within the script.

# TODO: Need to decide what to do with title and summary
title:
  description: "A short phrase or sentence describing the dataset."
  requirement: "Required."
  format: "text"
  value: "Some title"

summary:
  description: "A paragraph describing the dataset."
  requirement: "Required."
  format: "text"
  value: "Airborne hyperspectral point cloud data acquired with a HySpex Mjolnir VNIR (400–1000 nm) spectrometer mounted on Lufttransport's aircraft (Dornier DO228 POD). The sensor records 1800 spatial pixels per scan line with 186 spectral channels. Precise geolocation is derived from Applanix POS AV 410 navigation data and a 5 m DEM from the Norwegian Polar Institute, with raytracing used to produce 3D georeferenced point clouds linked to full spectra. Products can be visualised as point clouds, converted to 3D meshes, or rasterised to geocoded imagery. Applications include cryosphere, ocean, and vegetation studies, such as glacier mapping, snow property assessment, biomass estimation, and algal bloom detection."

keywords:
  description: "A comma-separated list of keywords or phrases."
  requirement: "Required, GCMD Science Keywords."
  format: "text"
  value: "Earth Science > Land Surface > Topography > Terrain Elevation > Digital Surface Model (DSM)"
  # Could be, for example
  # "Earth Science > Land Surface > Topography > Terrain Elevation > Digital Elevation/Terrain Model (DEM)"
  # "Earth Science > Cryosphere > Sea Ice > Sea Ice Elevation"
  # GCMD keywods can be found here: https://gcmd.earthdata.nasa.gov/KeywordViewer/

keywords_vocabulary:
  description: "The unique name or identifier of the vocabulary used for keywords. Example: 'GCMD'."
  requirement: "Required."
  format: "text"
  value: "GCMD:GCMD Keywords"

time_coverage_start:
  description: "The time of the first data point in the dataset. Use the ISO 8601:2004 format (YYYY-MM-DDTHH:MM:SSZ)."
  requirement: "Required."
  format: "text"
  value: ""

time_coverage_end:
  description: "The time of the last data point in the dataset. Use the ISO 8601:2004 format."
  requirement: "Required."
  format: "text"
  value: ""

Conventions:
  description: "A comma-separated string of conventions followed by the dataset. For ACDD, include 'ACDD-1.3'."
  requirement: "Required."
  format: "text"
  value: "CF-1.8, ACDD-1.3"

source:
  description: "The method of production of the original data. Example: 'temperature from CTD #1234'."
  requirement: "Optional."
  format: "text"
  value: ""

processing_level:
  description: "A textual description of the processing level of the data."
  requirement: "Optional."
  format: "text"
  value: ""

creator_type:
  description: "Specifies the type of creator (person, group, institution, or position)."
  requirement: "Required."
  format: "text"
  value: "person"

creator_institution:
  description: "The institution of the creator."
  requirement: "Required."
  format: "text"
  value: ""

creator_email:
  description: "The email of the creator."
  requirement: "Required."
  format: "text"
  value: ""

creator_name:
  description: "The name of the person (or creator type) responsible for the dataset."
  requirement: "Required."
  format: "text"
  value: ""

creator_url:
  description: "The URL of the person (or other creator type specified by the creator_type attribute) principally responsible for creating this data. See last paragraph under creator_type."
  requirement: "Required. Consistency across comma-separated lists for all creator_* attributes is required. Do not use ',' except for separating elements. Use this for principal investigator."
  format: "text"
  value: "" # Best practice is to use OrcID

institution:
  description: "The name of the institution principally responsible for originating this data. If provided as a string ending with a keyword in parentheses (), the main text will be interpreted as the long name and the keyword in the parentheses as the short name. E.g. 'Norwegian Meteorological Institute (MET)'"
  requirement: "Optional, not extracted to discovery metadata records."
  format: "text"
  value: ""

naming_authority:
  description: "The organization that provides the initial id (see above) for the dataset. The naming authority should be uniquely specified by this attribute. We recommend using reverse-DNS naming for the naming authority; URIs are also acceptable. Example: 'edu.ucar.unidata'."
  requirement: "Required if not hosted by MET."
  format: "text"
  value: "no.met.adc"

publisher_name:
  description: "The name of the person (or other entity specified by the publisher_type attribute) responsible for publishing the data file or product to users, with its current metadata and format."
  requirement: "Required if not hosted by MET. If not an organisation, add publisher_institution, which identifies the data centre hosting the dataset."
  format: "text"
  value: "Norwegian Meteorological Institute / Arctic Data Centre"

publisher_email:
  description: "The email address of the person (or other entity specified by the publisher_type attribute) responsible for publishing the data file or product to users, with its current metadata and format."
  requirement: "Required if not hosted by MET. Consistency across comma-separated lists is required."
  format: "text"
  value: "adc-support@met.no"

publisher_url:
  description: "The URL of the person (or other entity specified by the publisher_type attribute) responsible for publishing the data file or product to users, with its current metadata and format."
  requirement: "Required if not hosted by MET. Consistency across comma-separated lists is required."
  format: "text"
  value: "https://adc.met.no/"

publisher_institution:
  description: "The institution of the person (or other entity specified by the publisher_type attribute) responsible for publishing the data file or product to users, with its current metadata and format."
  requirement: "Required if not hosted by MET. Consistency across comma-separated lists is required."
  format: "text"
  value: "Norwegian Meteorological Institute"

project:
  description: "The name of the project(s) principally responsible for originating this data. Multiple projects can be separated by commas. If a sub-string includes a keyword in parentheses, the content within the parentheses is interpreted as the short name for the project while the rest is the long name. E.g. 'Nansen Legacy (NLEG)'."
  requirement: "Required."
  format: "text"
  value: ""

instrument:
  description: "Name of the contributing instrument(s) or sensor(s) used to create this dataset or product. Indicate controlled vocabulary used in instrument_vocabulary. Comma-separated list."
  requirement: "Optional."
  format: "text"
  value: ""

instrument_vocabulary:
  description: "Controlled vocabulary for the names used in the 'instrument' attribute. Comma-separated list."
  requirement: "Optional."
  format: "text"
  value: ""

references:
  description: "Published or web-based references that describe the data or methods used to produce it. Recommend URIs such as a URL or DOI for papers or other references. This attribute is defined in the CF conventions."
  requirement: "Optional."
  format: "text"
  value: ""

license:
  description: "Provide the URL to a standard or specific license, enter 'Freely Distributed' or 'None', or describe any restrictions to data access and distribution. Use identifiers and URLs from https://spdx.org/licenses/."
  requirement: "Required."
  format: "text"
  value: "https://creativecommons.org/licenses/by/4.0/"

iso_topic_category:
  description: "ISO topic category fetched from a controlled vocabulary. Accepted elements are listed in the MMD specification."
  requirement: "Recommended for filtering purposes. Not part of ACDD, MET extension."
  format: "text"
  choices: "farming; biota; boundaries; climatologyMeteorologyAtmosphere; economy; elevation; environment; geoscientificInformation; health; imageryBaseMapsEarthCover; intelligenceMilitary; inlandWaters; location; oceans; planningCadastre; society; structure; transportation; utilitiesCommunications; Not available"
  value: "" # Most likely "elevation" for natural structures or "structure" for man-made objects

operational_status:
  description: "The current operational status of the product. Only elements from the controlled vocabulary of the MMD specification are allowed."
  requirement: "Recommended for filtering purposes. Not part of ACDD, MET extension."
  format: "text"
  value: "Scientific"

featureType:
  description: "This is part of the CF conventions and is required when submitting data according to the discrete sampling geometries section of the CF conventions."
  requirement: "The keywords used have to be exactly written as in the CF conventions. Valid keywords are listed in the CF-Convention specification."
  format: "text"
  value: "point"
