# Configuration file for global attributes.
# Attributes commented out will be derived from the data file (bounding box of coordinates)
# or derived within the code (current timestamp for 'date_created' and 'history' attributes)
# Please see https://adc.met.no/node/4 for how to fill in the different attributes.
# More attributes can be added as new lines
id: # Required
naming_authority: # Required
title: # Required
summary: # Required
keywords: # Required
keywords_vocabulary: # Required
#geospatial_lat_min: # Required
#geospatial_lat_max: # Required
#geospatial_lon_min: # Required
#geospatial_lon_max: # Required
#geospatial_vertical_min: # Optional
#geospatial_vertical_max: # Optional
time_coverage_start: # Required
time_coverage_end: # Required
Conventions: 'CF-1.8, ACDD-1.3' # Required
#history: # Required
source: # Optional
processing_level: # Optional
#date_created: # Required
creator_type: # Required
creator_institution: # Required
creator_name: # Required
creator_email: # Required
creator_url: # Required
institution: # Optional
publisher_name: # Required
publisher_email: # Required
publisher_url: # Required
project: # Required
platform: # Recommended
platform_vocabulary: # Recommended
instrument: # Optional
instrument_vocabulary: # Optional
references: # Optional
license: 'https://creativecommons.org/licenses/by/4.0/' # Required
iso_topic_category: # Recommended
operational_status: 'Scientific' # Recommended