# This YAML file contains a dictionary where each key represents a target variable name
# and its corresponding value is a list of likely names that the user or software might
# have provided in their input file.

latitude:
  - latitude
  - lat
  - lat_deg
  - latitudinal
  - lat_decimal
  - lat_dd
  - latitude_deg
  - lat_degrees
  - lat_decimal_deg
  - lat_dec_deg

longitude:
  - longitude
  - lon
  - long
  - longitudinal
  - lon_decimal
  - lon_dd
  - longitude_deg
  - lon_degrees
  - lon_decimal_deg
  - lon_dec_deg

altitude:
  - altitude
  - alt
  - elev
  - elevation
  - alt_meters
  - height
  - alt_feet
  - above_sea_level
  - amsl

X:
  - x
  - x_coord
  - x_axis
  - x_position
  - x_val
  - x_coordinate
  - x_val_meters
  - x_val_feet

Y:
  - y
  - y_coord
  - y_axis
  - y_position
  - y_val
  - y_coordinate
  - y_val_meters
  - y_val_feet

Z:
  - z
  - z_coord
  - z_axis
  - z_position
  - z_val
  - z_coordinate
  - z_val_meters
  - z_val_feet

red:
  - red
  - red_value
  - r
  - red_channel
  - red_intensity
  - red_intensity_value
  - red_level

green:
  - green
  - green_value
  - g
  - green_channel
  - green_intensity
  - green_intensity_value
  - green_level

blue:
  - blue
  - blue_value
  - b
  - blue_channel
  - blue_intensity
  - blue_intensity_value
  - blue_level